version: '3.3'

services:

  python: &python
    build:
      context: ci-generator/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/ci-generator

  ci-generator-generate:
    <<: *python
    command: [ "sh", "-c", "python generate_gitlab_ci.py > ../.gitlab-ci.yml" ]

  ci-generator-update:
    <<: *python
    command: [ "sh", "-c", "python src/check_new_version.py > ./unity_versions.yml" ]

  ci-generator-test:
    <<: *python
    command: [ "sh", "-c", "coverage run -m unittest tests/test*.py" ]

  ci-generator-generate-snapshots:
    <<: *python
    command: [ "sh", "-c", "coverage run -m unittest tests/test*.py" ]
    environment:
      UPDATE_SNAPSHOTS: 'True'
